#!/bin/bash
set -e

NGINX_CONF="/etc/nginx/nginx.conf"

chmod a+w /var/www/runtime -R

echo "Running Nginx with configuration : $NGINX_CONF"
/usr/sbin/nginx -c $NGINX_CONF -t && exec nginx -c $NGINX_CONF
